name: Publish Docker image

on:
  push:
    # branches: # 仅 master 分支
    #   - master
    tags: # 仅带 tag:v* 时构建
      - v*
      # - V*
  schedule: # utc 21 点 北京时间 5点
    - cron: '0 21 * * *'

env:
  # 设置 docker 镜像名
  IMAGE_NAME: test
  IMAGE_ID: jasperhale/$IMAGE_NAME

jobs:
  path-context:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false # 持久凭证设置为false,actions/checkout@v2 需要

      - name: Set up QEMU # 多平台构建需要
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub # 登录 DockerHub
        uses: docker/login-action@v1
        with: # 获取用户名/密码
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version # 获取 Tag Version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          # 添加时间标签
          tags: |
            jasperhale/overture:latest
            jasperhale/overture:${{ steps.vars.outputs.tag }}
            jasperhale/overture:${{ steps.vars.outputs.tag }}-${{ steps.date.outputs.today }}
