name: Publish Docker image
on:
  push:
    branches: # 仅 master 分支
      - master
    # tags: # 仅带 tag:v* 时构建
    #   - v*

jobs:
  push-to-registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          path: /
          persist-credentials: false # 持久凭证设置为false,actions/checkout@v2 需要

      - name: Set up QEMU # 多平台构建需要
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub # 登录 DockerHub
        uses: docker/login-action@v1
        with: # 获取用户名/密码
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jasperhale/overture_test2:latest